pipeline {
    agent { docker { image 'python:3.10.10-alpine' } }
    environment {
        HOME = "${env.WORKSPACE}"
    }
    stages {
        stage('install requirements') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Create data') {
            steps {
                sh 'python3 data_creation.py'
            }
        }
    }
}