pipeline {
    agent { docker { image 'python:3.10.10-alpine' } }
    environment {
        HOME = "${env.WORKSPACE}"
    }
    stages {
        stage('install requirements') {
            steps {
                sh 'pip install -r lab2/jenkins/ml_pipeline/requirements.txt'
            }
        }
        stage('Create data') {
            steps {
                sh 'python3 lab2/jenkins/ml_pipeline/data_creation.py'
            }
        }
    }
}